export const EN = {
  navWork: 'Work', navCase: 'Case', navAbout: 'About', navContact: 'Contact',
  resume: 'Resume', downloadResume: 'Download resume', present: 'Present',
  kicker: 'Software Engineer · Surabaya, Indonesia',
  heroSub: '5+ years building web and mobile systems across manufacturing, startup, and port logistics environments — where the cost of a bug is real.',
  ctaEnter: 'Enter the yard', ctaHire: 'Hire me', scroll: 'Scroll to travel',
  secWork: 'WORK', workTitle: 'Systems in production',
  workIntro: 'Port logistics, fuel operations, POS and CRM products, enterprise HR. Legacy stacks and modern ones, usually talking to each other.',
  p1: 'Rebuilt legacy APBS as Portal APBS using ASP.NET Core 8 for vessel permit requests, integrated with TPS, PTOS-M, PTOS-PK, PKK, and TTL.',
  p2: 'ASP.NET Core 3 gateway handling JSON-to-JSON integration between internal systems and SAP.',
  p3: 'Web application handling fuel (BBM) request workflows and reporting, plus a Flutter app letting port staff manage fuel operations remotely.',
  p4: '.NET Framework system to manage container flow in and out of port depots, improving operational visibility.',
  p5: 'Fullstack web app managing corporate lending workflows for Pelindo Group and non-Pelindo companies, including submission, approval, and financial reporting modules.',
  p6: 'Java Android POS apps with Node.js and CodeIgniter 3 backends, a Flutter loyalty platform, and Wooblazz CRM for tracking sales team performance and attendance.',
  secCase: 'CASE STUDY',
  caseBody: 'Vessel permit requests used to run through a legacy APBS installation. The rebuild moved it to ASP.NET Core 8 and wired it into the systems the port actually runs on — TPS, PTOS-M, PTOS-PK, PKK, and TTL.',
  lblRole: 'ROLE', valRole: 'Developer / architecture & docs', lblStack: 'STACK',
  lblIntegrations: 'INTEGRATIONS', lblYear: 'YEAR', valYear: '2024 – present',
  stat1: 'EXTERNAL SYSTEMS INTEGRATED', stat2: 'SYSTEMS SHIPPED AT PELINDO',
  secProcess: 'PROCESS',
  pr1t: 'Read the legacy', pr1b: 'Comfortable in legacy codebases — a PHP Native system from 2012 gets read before anything gets rewritten.',
  pr2t: 'Design for maintenance', pr2b: 'System architecture and folder structures built for long-term scalability, with clear documentation for future developers.',
  pr3t: 'Integrate', pr3b: 'SAP, REST APIs, XML/JSON conversion, and hardware like fingerprint machines and Hikvision access control.',
  pr4t: 'Harden it', pr4b: 'Robust error handling, performance optimization, and unit testing so production stays stable.',
  secAbout: 'ABOUT',
  aboutLead: 'Started with HR and attendance automation, moved into startup POS and CRM products, and now working on mission-critical port infrastructure — integrating legacy systems like SAP and .NET Framework with modern stacks like ASP.NET Core 8 and Flutter.',
  aboutBody: 'Most of the work has been in environments where the cost of a bug is real — port operations, fuel logistics, enterprise HR — so production stability and clean documentation are not optional habits.',
  skills: 'TECHNICAL SKILLS', skLang: 'LANGUAGES', skBackend: 'BACKEND', skFront: 'FRONTEND & MOBILE',
  skData: 'DATA & DEVOPS', skIntegration: 'INTEGRATION', skEdu: 'EDUCATION',
  edu1: 'B.Sc. Information Systems, Institut Teknologi Adhi Tama Surabaya (2025)',
  edu2: 'Diploma in Information Systems, Universitas Airlangga (2021)',
  secCerts: 'CERTIFICATIONS', secContact: 'CONTACT',
  contactTitle1: 'Available for', contactTitle2: 'freelance builds',
};

// ponytail: this type is the translation check — a missing or misspelled ID key
// fails `tsc` in CI, so no runtime key-parity test is needed.
export const ID: Record<keyof typeof EN, string> = {
  navWork: 'Karya', navCase: 'Studi Kasus', navAbout: 'Tentang', navContact: 'Kontak',
  resume: 'CV', downloadResume: 'Unduh CV', present: 'Sekarang',
  kicker: 'Software Engineer · Surabaya, Indonesia',
  heroSub: 'Lebih dari 5 tahun membangun sistem web dan mobile di lingkungan manufaktur, startup, dan logistik pelabuhan — tempat di mana satu bug punya biaya nyata.',
  ctaEnter: 'Masuk ke yard', ctaHire: 'Hubungi saya', scroll: 'Gulir untuk menjelajah',
  secWork: 'KARYA', workTitle: 'Sistem yang berjalan di produksi',
  workIntro: 'Logistik pelabuhan, operasional BBM, produk POS dan CRM, HR perusahaan. Stack lama dan modern, biasanya harus saling berbicara.',
  p1: 'Membangun ulang APBS lama menjadi Portal APBS dengan ASP.NET Core 8 untuk permohonan izin kapal, terintegrasi dengan TPS, PTOS-M, PTOS-PK, PKK, dan TTL.',
  p2: 'Gateway ASP.NET Core 3 yang menangani integrasi JSON-to-JSON antara sistem internal dan SAP.',
  p3: 'Aplikasi web untuk alur permintaan BBM dan pelaporannya, dilengkapi aplikasi Flutter agar staf pelabuhan bisa mengelola operasional BBM dari mana saja.',
  p4: 'Sistem .NET Framework untuk mengelola arus kontainer masuk dan keluar depo pelabuhan, meningkatkan visibilitas operasional.',
  p5: 'Aplikasi web fullstack untuk alur pinjaman korporasi Pelindo Group dan perusahaan non-Pelindo, mencakup modul pengajuan, persetujuan, dan pelaporan keuangan.',
  p6: 'Aplikasi POS Java Android dengan backend Node.js dan CodeIgniter 3, platform loyalty berbasis Flutter, serta Wooblazz CRM untuk memantau kinerja dan kehadiran tim sales.',
  secCase: 'STUDI KASUS',
  caseBody: 'Permohonan izin kapal sebelumnya berjalan di instalasi APBS lama. Pembangunan ulang memindahkannya ke ASP.NET Core 8 dan menyambungkannya ke sistem yang benar-benar dipakai pelabuhan — TPS, PTOS-M, PTOS-PK, PKK, dan TTL.',
  lblRole: 'PERAN', valRole: 'Developer / arsitektur & dokumentasi', lblStack: 'STACK',
  lblIntegrations: 'INTEGRASI', lblYear: 'TAHUN', valYear: '2024 – sekarang',
  stat1: 'SISTEM EKSTERNAL TERINTEGRASI', stat2: 'SISTEM DIKIRIM DI PELINDO',
  secProcess: 'PROSES',
  pr1t: 'Baca kode lamanya', pr1b: 'Nyaman bekerja di codebase lama — sistem PHP Native dari 2012 dibaca dulu sebelum ada yang ditulis ulang.',
  pr2t: 'Rancang untuk dirawat', pr2b: 'Arsitektur sistem dan struktur folder yang disiapkan untuk skala jangka panjang, dengan dokumentasi jelas bagi developer berikutnya.',
  pr3t: 'Integrasikan', pr3b: 'SAP, REST API, konversi XML/JSON, dan perangkat seperti mesin fingerprint serta akses kontrol Hikvision.',
  pr4t: 'Perkuat', pr4b: 'Penanganan error yang solid, optimasi performa, dan unit testing agar produksi tetap stabil.',
  secAbout: 'TENTANG',
  aboutLead: 'Mulai dari otomasi HR dan absensi, lanjut ke produk POS dan CRM startup, dan sekarang menangani infrastruktur pelabuhan yang kritikal — mengintegrasikan sistem lama seperti SAP dan .NET Framework dengan stack modern seperti ASP.NET Core 8 dan Flutter.',
  aboutBody: 'Sebagian besar pekerjaan berada di lingkungan di mana biaya sebuah bug itu nyata — operasional pelabuhan, logistik BBM, HR perusahaan — sehingga stabilitas produksi dan dokumentasi yang bersih bukan kebiasaan opsional.',
  skills: 'KEAHLIAN TEKNIS', skLang: 'BAHASA', skBackend: 'BACKEND', skFront: 'FRONTEND & MOBILE',
  skData: 'DATA & DEVOPS', skIntegration: 'INTEGRASI', skEdu: 'PENDIDIKAN',
  edu1: 'S1 Sistem Informasi, Institut Teknologi Adhi Tama Surabaya (2025)',
  edu2: 'D3 Sistem Informasi, Universitas Airlangga (2021)',
  secCerts: 'SERTIFIKASI', secContact: 'KONTAK',
  contactTitle1: 'Tersedia untuk', contactTitle2: 'proyek freelance',
};

export type Lang = 'EN' | 'ID';
export type Copy = typeof EN;
export const COPY: Record<Lang, Copy> = { EN, ID };
